import Verbose.Tactics.Notations
import Verbose.Catalan.Assume
import Verbose.Catalan.By
import Verbose.Catalan.Calc
import Verbose.Catalan.Claim
import Verbose.Catalan.Fix
import Verbose.Catalan.Lets
import Verbose.Catalan.Since
import Verbose.Catalan.We
import Verbose.Catalan.Widget
import Verbose.Catalan.Statements
